version: '3.1'

services:

  db-traffic-speed-model:
    image: postgis/postgis:15-3.3-alpine
    restart: always
    container_name: db-traffic-speed-model
    user: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-backup:/db-backup
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env

volumes:
  db-data:
